require "user.impatient" -- should be top...
require "user.autocommands"
require "user.autopairs"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.indentline"
require "user.keymaps"
require "user.lsp"
require "user.lualine"
require "user.me"
require "user.nvim-tree"
require "user.options"
require "user.plugins"
require "user.toggleterm"
require "user.treesitter"
require "user.whichkey"
