theme = "tokyonight"

[editor]
# line-number = "relative"
# mouse = false

[editor.cursor-shape]
# insert = "bar"
# normal = "block"
# select = "underline"

[editor.file-picker]
# hidden = false

[keys.normal]
Z = { Z = ":write-quit", Q = ":quit!" }
C-w = ":w"
C-f = ":sh kitty @ launch --no-response --copy-env --cwd=current --type=window lf"
# "C-/" = ":sh kitty @ launch --no-response --copy-env --hold --cwd=current --type=overlay lf"
# C-t = ":sh kitty @ launch --no-response --copy-env --hold --cwd=current --type=tab mix test"
# C-T = ":sh kitty @ launch --no-response --copy-env --hold --cwd=current --type=tab pnpm test"


[keys.insert]
"C-b" = "move_char_left"
"C-f" = "move_char_right"
"A-b" = "move_prev_word_end"
"C-left" = "move_prev_word_end"
"A-f" = "move_next_word_start"
"C-right" = "move_next_word_start"
"A-<" = "goto_file_start"
"A->" = "goto_file_end"
"pageup" = "page_up"
"pagedown" = "page_down"
"home" = "goto_line_start"
"C-a" = "goto_line_start"
"end" = "goto_line_end_newline"
"C-e" = "goto_line_end_newline"
"A-left" = "goto_line_start"

"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
